import { Business, Service, Counter, Staff, QueueTicket, HourlyAnalytics } from '@/types';

export const DEMO_BUSINESS: Business = {
  id: 'biz-city-care-01',
  name: 'City Care Clinic',
  slug: 'city-care-clinic',
  category: 'Clinic & Diagnostics',
  address: '402 Health Avenue, Medical District, Suite 100',
  phone: '+91 98765 43210',
  description: 'Multi-specialty primary health and diagnostic care center providing streamlined outpatient services.',
  operating_hours: '08:30 AM – 07:30 PM (Mon – Sat)',
  status: 'OPEN',
  created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
};

export const DEMO_SERVICES: Service[] = [
  {
    id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    name: 'General Consultation',
    description: 'Routine physician consultation, prescription renewals and preventive checkups.',
    average_duration: 8,
    max_queue_size: 50,
    online_joining: true,
    active: true,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'srv-blood-test',
    business_id: 'biz-city-care-01',
    name: 'Blood Test & Diagnostics',
    description: 'Pathology sample collection, lipid profile, CBC, and rapid diagnostic panels.',
    average_duration: 5,
    max_queue_size: 40,
    online_joining: true,
    active: true,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'srv-follow-up',
    business_id: 'biz-city-care-01',
    name: 'Follow-up & Report Review',
    description: 'Doctor review of lab investigations and recovery progress assessment.',
    average_duration: 6,
    max_queue_size: 30,
    online_joining: true,
    active: true,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_COUNTERS: Counter[] = [
  {
    id: 'cnt-01',
    business_id: 'biz-city-care-01',
    name: 'Counter 1 (Room 101)',
    service_id: 'srv-gen-consult',
    active: true,
    current_ticket_id: 'tkt-36',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'cnt-02',
    business_id: 'biz-city-care-01',
    name: 'Counter 2 (Room 102)',
    service_id: 'srv-gen-consult',
    active: true,
    current_ticket_id: undefined,
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_STAFF: Staff[] = [
  {
    id: 'stf-01',
    business_id: 'biz-city-care-01',
    name: 'Dr. Shah',
    email: 'dr.shah@citycare.com',
    role: 'STAFF',
    counter_id: 'cnt-01',
    service_id: 'srv-gen-consult',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'stf-02',
    business_id: 'biz-city-care-01',
    name: 'Dr. Patel',
    email: 'dr.patel@citycare.com',
    role: 'STAFF',
    counter_id: 'cnt-02',
    service_id: 'srv-gen-consult',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: 'stf-admin',
    business_id: 'biz-city-care-01',
    name: 'Admin Desk',
    email: 'admin@citycare.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_DEMO_TICKETS: QueueTicket[] = [
  {
    id: 'tkt-36',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Ananya Verma',
    whatsapp_number: '+91 98201 12345',
    token_number: 36,
    secure_token: 'q-tk-36-ananya-89f1',
    counter_id: 'cnt-01',
    counter_name: 'Counter 1 (Room 101)',
    status: 'SERVING',
    joined_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    called_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    service_started_at: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-37',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Vikram Sengupta',
    whatsapp_number: '+91 98310 98765',
    token_number: 37,
    secure_token: 'q-tk-37-vikram-71b2',
    counter_id: 'cnt-01',
    counter_name: 'Counter 1 (Room 101)',
    status: 'CALLED',
    joined_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    called_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-38',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Amit Joshi',
    whatsapp_number: '+91 98450 33445',
    token_number: 38,
    secure_token: 'q-tk-38-amit-44c3',
    status: 'WAITING',
    joined_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-39',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Priya Nambiar',
    whatsapp_number: '+91 98711 55667',
    token_number: 39,
    secure_token: 'q-tk-39-priya-90d4',
    status: 'WAITING',
    joined_at: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-40',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Jayant Kulkarni',
    whatsapp_number: '+91 98922 77889',
    token_number: 40,
    secure_token: 'q-tk-40-jayant-33e5',
    status: 'WAITING',
    joined_at: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-41',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Sneha Deshmukh',
    whatsapp_number: '+91 98199 66778',
    token_number: 41,
    secure_token: 'q-tk-41-sneha-12f6',
    status: 'WAITING',
    joined_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'tkt-42',
    queue_id: 'q-gen-consult',
    service_id: 'srv-gen-consult',
    business_id: 'biz-city-care-01',
    user_name: 'Rahul Sharma (You)',
    whatsapp_number: '+91 98765 43210',
    token_number: 42,
    secure_token: 'q-tk-42-rahul-you-a1b2',
    status: 'WAITING',
    joined_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
];

export const DEMO_HOURLY_ANALYTICS: HourlyAnalytics[] = [
  { hour: '9 AM', hourNum: 9, customersServed: 14, avgWaitMinutes: 12, avgServiceMinutes: 7, peakQueueLength: 6 },
  { hour: '10 AM', hourNum: 10, customersServed: 22, avgWaitMinutes: 19, avgServiceMinutes: 8, peakQueueLength: 10 },
  { hour: '11 AM', hourNum: 11, customersServed: 31, avgWaitMinutes: 26, avgServiceMinutes: 8, peakQueueLength: 13 },
  { hour: '12 PM', hourNum: 12, customersServed: 28, avgWaitMinutes: 24, avgServiceMinutes: 9, peakQueueLength: 12 },
  { hour: '1 PM', hourNum: 13, customersServed: 15, avgWaitMinutes: 14, avgServiceMinutes: 7, peakQueueLength: 7 },
  { hour: '2 PM', hourNum: 14, customersServed: 18, avgWaitMinutes: 16, avgServiceMinutes: 8, peakQueueLength: 8 },
  { hour: '3 PM', hourNum: 15, customersServed: 24, avgWaitMinutes: 21, avgServiceMinutes: 8, peakQueueLength: 11 },
  { hour: '4 PM', hourNum: 16, customersServed: 33, avgWaitMinutes: 28, avgServiceMinutes: 9, peakQueueLength: 14 },
  { hour: '5 PM', hourNum: 17, customersServed: 39, avgWaitMinutes: 34, avgServiceMinutes: 8, peakQueueLength: 16 },
  { hour: '6 PM', hourNum: 18, customersServed: 37, avgWaitMinutes: 31, avgServiceMinutes: 8, peakQueueLength: 14 },
  { hour: '7 PM', hourNum: 19, customersServed: 21, avgWaitMinutes: 18, avgServiceMinutes: 7, peakQueueLength: 9 },
];
